### ISSUE TITLE
Anh ơi cái này có chạy được trên CPU k anh

### ISSUE THREAD

**Issue by nguyenquanghieu2000d** [huyhoang17/DB_text_minimal#14]
Anh ơi cái này có chạy được trên CPU k anh

**Comment by huyhoang17** [comment]
@nguyenquanghieu2000d  model có chạy đc trên cpu bạn nhé, hiện tại trên repo mình chưa upload pre-trained model lên

**Comment by nguyenquanghieu2000d** [comment]
@huyhoang17  vâng em cảm ơn anh
