### ISSUE TITLE
from clova_ocr.dataset import test_preprocess as rec_preprocess

### ISSUE THREAD

**Issue by vuminhduc97** [huyhoang17/DB_text_minimal#18]
bạn ơi cho mình xin test_preprocess function với. Trên clova_ocr.dataset clova đã xóa hàm này rồi

**Comment by huyhoang17** [comment]
@vuminhduc97 bạn tham khảo đoạn code này nhé: https://pikab.in/3552c17264

**Comment by vuminhduc97** [comment]
cảm ơn b nhé

**Comment by khanh14ph** [comment]
link đoạn code anh gửi ở trên không vào được nữa ạ, anh có thể chia sẻ một link khác được ko ạ ?
